updating design and index page
foss-events/website pull request #178
Opened 2020-10-22 01:15 UTC by dreirik

* updated front-page to show online events in style "NAME by ORGA (COUNTRY)"
* Included new country-codes for EU and International
* database: 
  * renamed "online" into "presentation form"
  * removed old columns not in use
  * renamed "conferences" into "events"
  * updated more details for the new look

2020-10-22 06:42 UTC, weeman1337 requested changes

2020-10-22 06:42 UTC, weeman1337 commented on generator/consts.py
> +iso_label_dict = {
Jetzt heißt es auf einmal wieder `iso_label_dict`.  
Du hattest dir extra gewünscht, dass es `iso_3166_countries` heißt ;)

2020-10-22 06:42 UTC, weeman1337 commented on generator/consts.py
> -iso_639_languages = {
Wieso löschst du die Sprach-Codes wieder raus?

2020-10-22 06:42 UTC, weeman1337 commented on generator/consts.py
> +    'SQ': 'Albania',
Der ist dann wieder falsch. Richtig ist `AL`. [1]

[1] https://de.wikipedia.org/wiki/ISO-3166-1-Kodierliste

2020-10-22 10:08 UTC, dreirik commented
sorry, das war ein copy-past-fehler weil ich mit einer alten version von costs.py gearbeitet habe. danke fürs feststellen, sollte jetzt passen.

2020-10-25 14:03 UTC, weeman1337 requested changes

2020-10-25 14:03 UTC, weeman1337 commented on generator/consts.py
> +    'EU': 'Europe',
Korrekt wäre European Union

2020-10-25 14:03 UTC, weeman1337 commented on generator/parser.py
> +from consts import iso_label_dict, months
Hier muss `iso_3166_countries` hin.  
Betrifft auch einige andere Stellen.

2020-10-25 14:03 UTC, weeman1337 commented on src/templates/partials/event-list-item-online.html
> +        {% if event['main_organiser'] %}
So Code-Style mäßig hängt das auf halb Acht ;)

2020-10-25 14:03 UTC, weeman1337 commented on src/templates/partials/event-list-item-online.html
> +			by {{ event['main_organiser'] }}
Interessiert das in der Übersicht? Braucht doch nur Platz..

2020-10-26 06:55 UTC, weeman1337 approved these changes

2020-10-26 16:32 UTC, merged